# Generated by Django 5.0.2 on 2024-02-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_remove_recipe_category_recipe_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='image',
            new_name='body_image',
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to='site_images/'),
        ),
    ]
